# --------------------------------
# Geyser Configuration File
#
# A bridge between Minecraft: Bedrock Edition and Minecraft: Java Edition.
#
# GitHub: https://github.com/GeyserMC/Geyser
# Discord: https://discord.geysermc.org/
# --------------------------------

bedrock:
  # The IP address that will listen for connections.
  # There is no reason to change this unless you want to limit what IPs can connect to your server.
  address: 0.0.0.0
  # The port that will listen for connections
  port: 19132
  # Some hosting services change your Java port everytime you start the server and require the same port to be used for Bedrock.
  # This option makes the Bedrock port the same as the Java port every time you start the server.
  # This option is for the plugin version only.
  clone-remote-port: false
  # The MOTD that will be broadcasted to Minecraft: Bedrock Edition clients. This is irrelevant if "passthrough-motd" is set to true
  # If either of these are empty, the respective string will default to "Geyser"
  motd1: "Geyser"
  motd2: "Geyser Server"
  # The Server Name that will be sent to Minecraft: Bedrock Edition clients. This is visible in both the pause menu and the settings menu.
  server-name: "Geyser"
  # How much to compress network traffic to the Bedrock client. The higher the number, the more CPU usage used, but
  # the smaller the bandwidth used. Does not have any effect below -1 or above 9. Set to -1 to disable.
  compression-level: 6
  # Whether to enable PROXY protocol or not for clients. You DO NOT WANT this feature unless you run UDP reverse proxy
  # in front of your Geyser instance.
  enable-proxy-protocol: false
  # A list of allowed PROXY protocol speaking proxy IP addresses/subnets. Only effective when "enable-proxy-protocol" is enabled, and
  # should really only be used when you are not able to use a proper firewall (usually true with shared hosting providers etc.).
  # Keeping this list empty means there is no IP address whitelist.
  # Both IP addresses and subnets are supported.
  #proxy-protocol-whitelisted-ips: [ "127.0.0.1", "172.18.0.0/16" ]
remote:
  # The IP address of the remote (Java Edition) server
  # If it is "auto", for standalone version the remote address will be set to 127.0.0.1,
  # for plugin versions, it is recommended to keep this as "auto" so Geyser will automatically configure address, port, and auth-type.
  # Leave as "auto" if floodgate is installed.
  address: auto
  # The port of the remote (Java Edition) server
  # For plugin versions, if address has been set to "auto", the port will also follow the server's listening port.
  port: 25565
  # Authentication type. Can be offline, online, or floodgate (see https://github.com/GeyserMC/Geyser/wiki/Floodgate).
  # For plugin versions, it's recommended to keep the `address` field to "auto" so Floodgate support is automatically configured.
  # If Floodgate is installed and `address:` is set to "auto", then "auth-type: floodgate" will automatically be used.
  auth-type: online
  # Allow for password-based authentication methods through Geyser. Only useful in online mode.
  # If this is false, users must authenticate to Microsoft using a code provided by Geyser on their desktop.
  allow-password-authentication: true
  # Whether to enable PROXY protocol or not while connecting to the server.
  # This is useful only when:
  # 1) Your server supports PROXY protocol (it probably doesn't)
  # 2) You run Velocity or BungeeCord with the option enabled in the proxy's main config.
  # IF YOU DON'T KNOW WHAT THIS IS, DON'T TOUCH IT!
  use-proxy-protocol: false
  # Forward the hostname that the Bedrock client used to connect over to the Java server
  # This is designed to be used for forced hosts on proxies
  forward-hostname: false

# Allows the overworld world height to be extended from 0 - 255 to -64 - 319. This option cannot be changed during a reload.
# Performance issues and/or additional bugs may occur for Bedrock clients as this is an experimental toggle on their end.
extended-world-height: false

# Floodgate uses encryption to ensure use from authorised sources.
# This should point to the public key generated by Floodgate (BungeeCord, Spigot or Velocity)
# You can ignore this when not using Floodgate.
# If you're using a plugin version of Floodgate on the same server, the key will automatically be picked up from Floodgate.
floodgate-key-file: key.pem

# The Xbox/Minecraft Bedrock username is the key for the Java server auth-info.
# This allows automatic configuration/login to the remote Java server.
# If you are brave enough to put your Mojang account info into a config file.
# Uncomment the lines below to enable this feature.
#userAuths:
#  BedrockAccountUsername: # Your Minecraft: Bedrock Edition username
#    email: javaccountemail@example.com # Your Minecraft: Java Edition email
#    password: javaccountpassword123 # Your Minecraft: Java Edition password
#    microsoft-account: true # Whether the account is a Mojang or Microsoft account.
#
#  bluerkelp2:
#    email: not_really_my_email_address_mr_minecrafter53267@gmail.com
#    password: "this isn't really my password"
#    microsoft-account: false

# Bedrock clients can freeze when opening up the command prompt for the first time if given a lot of commands.
# Disabling this will prevent command suggestions from being sent and solve freezing for Bedrock clients.
command-suggestions: true

# The following three options enable "ping passthrough" - the MOTD, player count and/or protocol name gets retrieved from the Java server.
# Relay the MOTD from the remote server to Bedrock players.
passthrough-motd: false
# Relay the protocol name (e.g. BungeeCord [X.X], Paper 1.X) - only really useful when using a custom protocol name!
# This will also show up on sites like MCSrvStatus. <mcsrvstat.us>
passthrough-protocol-name: false
# Relay the player count and max players from the remote server to Bedrock players.
passthrough-player-counts: false
# Enable LEGACY ping passthrough. There is no need to enable this unless your MOTD or player count does not appear properly.
# This option does nothing on standalone.
legacy-ping-passthrough: false
# How often to ping the remote server, in seconds. Only relevant for standalone or legacy ping passthrough.
# Increase if you are getting BrokenPipe errors.
ping-passthrough-interval: 3

# Whether to forward player ping to the server. While enabling this will allow Bedrock players to have more accurate
# ping, it may also cause players to time out more easily.
forward-player-ping: false

# Maximum amount of players that can connect. This is only visual at this time and does not actually limit player count.
max-players: 100

# If debug messages should be sent through console
debug-mode: false

# Thread pool size
general-thread-pool: 32

# Allow third party capes to be visible. Currently allowing:
# OptiFine capes, LabyMod capes, 5Zig capes and MinecraftCapes
allow-third-party-capes: true

# Allow third party deadmau5 ears to be visible. Currently allowing:
# MinecraftCapes
allow-third-party-ears: false

# Allow a fake cooldown indicator to be sent. Bedrock players do not see a cooldown as they still use 1.8 combat
# Can be title, actionbar or false
show-cooldown: title

# Controls if coordinates are shown to players.
show-coordinates: true

# If set, when a Bedrock player performs any emote, it will swap the offhand and mainhand items, just like the Java Edition keybind
# There are three options this can be set to:
# disabled - the default/fallback, which doesn't apply this workaround
# no-emotes - emotes will NOT be sent to other Bedrock clients and offhand will be swapped. This effectively disables all emotes from being seen.
# emotes-and-offhand - emotes will be sent to Bedrock clients and offhand will be swapped
emote-offhand-workaround: "disabled"

# The default locale if we dont have the one the client requested. Uncomment to not use the default system language.
# default-locale: en_us

# Specify how many days images will be cached to disk to save downloading them from the internet.
# A value of 0 is disabled. (Default: 0)
cache-images: 0

# Allows custom skulls to be displayed. Keeping them enabled may cause a performance decrease on older/weaker devices.
allow-custom-skulls: true

# Whether to add (at this time, only) the furnace minecart as a separate item in the game, which normally does not exist in Bedrock Edition.
# This should only need to be disabled if using a proxy that does not use the "transfer packet" style of server switching.
# If this is disabled, furnace minecart items will be mapped to hopper minecart items.
# This option requires a restart of Geyser in order to change its setting.
add-non-bedrock-items: true

# Bedrock prevents building and displaying blocks above Y127 in the Nether -
# enabling this config option works around that by changing the Nether dimension ID
# to the End ID. The main downside to this is that the sky will resemble that of
# the end sky in the nether, but ultimately it's the only way for this feature to work.
above-bedrock-nether-building: false

# Force clients to load all resource packs if there are any.
# If set to false, it allows the user to connect to the server even if they don't
# want to download the resource packs.
force-resource-packs: true

# Allows Xbox achievements to be unlocked.
# THIS DISABLES ALL COMMANDS FROM SUCCESSFULLY RUNNING FOR BEDROCK IN-GAME, as otherwise Bedrock thinks you are cheating.
xbox-achievements-enabled: false

# bStats is a stat tracker that is entirely anonymous and tracks only basic information
# about Geyser, such as how many people are online, how many servers are using Geyser,
# what OS is being used, etc. You can learn more about bStats here: https://bstats.org/.
# https://bstats.org/plugin/server-implementation/GeyserMC
metrics:
  # If metrics should be enabled
  enabled: true
  # UUID of server, don't change!
  uuid: generateduuid

# ADVANCED OPTIONS - DO NOT TOUCH UNLESS YOU KNOW WHAT YOU ARE DOING!

# Geyser updates the Scoreboard after every Scoreboard packet, but when Geyser tries to handle
# a lot of scoreboard packets per second can cause serious lag.
# This option allows you to specify after how many Scoreboard packets per seconds
# the Scoreboard updates will be limited to four updates per second.
scoreboard-packet-threshold: 20

custom-model-data-mappings:
  # "oraxen_item_id;is_this_a_tool" (pickaxe,sword,etc.)
  # replace entries below with your own oraxen items
  - "amber_axe;true"
  - "amber_boots;false"
  - "amber_chestplate;false"
  - "amber_helmet;false"
  - "amber_hoe;true"
  - "amber_leggings;false"
  - "amber_pickaxe;true"
  - "amber_spade;true"
  - "amber_sword;true"
  - "amber;false"
  - "amethyst_axe;true"
  - "amethyst_boots;false"
  - "amethyst_chestplate;false"
  - "amethyst_hammer;true"
  - "amethyst_helmet;false"
  - "amethyst_hoe;true"
  - "amethyst_leggings;false"
  - "amethyst_pickaxe;true"
  - "amethyst_spade;true"
  - "amethyst_sword;true"
  - "amethyst;false"
  - "aquamarine_chronitium_sword;true"
  - "aquamarine;false"
  - "arrow_next_icon;false"
  - "arrow_previous_icon;false"
  - "assassins_boots;false"
  - "assassins_chestplate;false"
  - "assassins_dagger;true"
  - "assassins_helmet;false"
  - "assassins_leggings;false"
  - "axe_of_the_souless;true"
  - "axe_of_warlords;true"
  - "banana_bread;false"
  - "banana_cake;false"
  - "banana;false"
  - "blueberry_pie;false"
  - "blueberry;false"
  - "cappuccino;false"
  - "chcolate_cookie;false"
  - "cherry_pie;false"
  - "cherry;false"
  - "chocolate_cake;false"
  - "chocolate_cupcake;false"
  - "chocolate;false"
  - "chronitium_axe;true"
  - "chronitium_dust;false"
  - "chronitium_hoe;true"
  - "chronitium_ingot;false"
  - "chronitium_pickaxe;true"
  - "chronitium_spade;true"
  - "chronitium_sword;true"
  - "cobalt_axe;true"
  - "cobalt_boots;false"
  - "cobalt_chestplate;false"
  - "cobalt_helmet;false"
  - "cobalt_hoe;true"
  - "cobalt_ingot;false"
  - "cobalt_leggings;false"
  - "cobalt_pickaxe;true"
  - "cobalt_spade;true"
  - "cobalt_sword;true"
  - "coffee_bean;false"
  - "coffee_cup;false"
  - "coffee;false"
  - "copper_shortsword;true"
  - "amethyst;false"
  - "anubis_head;false"
  - "azure_sabre;true"
  - "battle_axe;true"
  - "bedrock_pickaxe;true"
  - "blade_of_the_silent;true"
  - "blood_sword;true"
  - "bloodyvengeance;true"
  - "bone_sword;true"
  - "cart;false"
  - "chair;false"
  - "claymore;true"
  - "coach;false"
  - "combat_bow;false"
  - "crown;false"
  - "dagger;true"
  - "diamond_katana;true"
  - "divine_shield;false"
  - "divine_sword;true"
  - "dragon;true"
  - "earth_hammer;true"
  - "energy_crystal_sword;true"
  - "goblin_beetle;true"
  - "golden_chokuto;true"
  - "great_sword;true"
  - "ice_staff;true"
  - "iron_uchigatana;true"
  - "katana;true"
  - "kings_blade;true"
  - "knight_shield;false"
  - "legendary_hammer;true"
  - "magic_book;true"
  - "magical_axe;true"
  - "magical_wand;true"
  - "musket;false"
  - "octavia_sword;true"
  - "pharaoh_head;false"
  - "shelf;false"
  - "shield;false"
  - "space_helmet;false"
  - "stone_broadsword;true"
  - "table;false"
  - "stage0;false"
  - "stage1;false"
  - "stage2;false"
  - "stage3;false"
  - "witch_hat;false"
  - "withooker;true"
  - "wood_sword;true"
  - "wooden_shortsword;true"
  - "diamond_cog;false"
  - "emerald_boots;false"
  - "emerald_chestplate;false"
  - "emerald_hammer;true"
  - "emerald_helmet;false"
  - "emerald_leggings;false"
  - "emerald_sword;true"
  - "exit_icon;false"
  - "fire_hammer;true"
  - "fireball;false"
  - "fried_egg;false"
  - "glass_sword;true"
  - "gold_cog;false"
  - "gold_shortsword;true"
  - "grape_seeds;false"
  - "grape;false"
  - "green_apple;false"
  - "ice_sword;true"
  - "icelord_boots;false"
  - "icelord_chestplate;false"
  - "icelord_helmet;false"
  - "icelord_leggings;false"
  - "iron_cog;false"
  - "iron_serpe;true"
  - "shield;false"
  - "jade;false"
  - "lemon_cake;false"
  - "lemon;false"
  - "lime;false"
  - "mango;false"
  - "miner_sandwitch;false"
  - "molten_iron_sword;true"
  - "musket_ball;false"
  - "obsidian_boots;false"
  - "obsidian_chestplate;false"
  - "obsidian_helmet;false"
  - "obsidian_leggings;false"
  - "obsidian_pickaxe;true"
  - "obsidian_sword;true"
  - "onyx_axe;true"
  - "onyx_boots;false"
  - "onyx_chestplate;false"
  - "onyx_hammer;true"
  - "onyx_helmet;false"
  - "onyx_hoe;true"
  - "onyx_leggings;false"
  - "onyx_pickaxe;true"
  - "onyx_spade;true"
  - "onyx_sword;true"
  - "onyx;false"
  - "orange;false"
  - "orax_hammer;true"
  - "orax;false"
  - "pear;false"
  - "pirate_sword;true"
  - "plum;false"
  - "pomegranate;false"
  - "raw_cobalt_ore;false"
  - "ruby_boots;false"
  - "ruby_chestplate;false"
  - "ruby_helmet;false"
  - "ruby_leggings;false"
  - "ruby;false"
  - "sapphire_axe;true"
  - "sapphire_boots;false"
  - "sapphire_chestplate;false"
  - "sapphire_helmet;false"
  - "sapphire_hoe;true"
  - "sapphire_leggings;false"
  - "sapphire_pickaxe;true"
  - "sapphire_spade;true"
  - "sapphire_sword;true"
  - "sapphire;false"
  - "scythe_of_death;true"
  - "soulessknight_boots;false"
  - "soulessknight_chestplate;false"
  - "soulessknight_helmet;false"
  - "soulessknight_leggings;false"
  - "steel_sword;true"
  - "strawberry_cake;false"
  - "strawberry_cupcake;false"
  - "strawberry_pie;false"
  - "strawberry;false"
  - "sword_of_the_titans;true"
  - "titanium_axe;true"
  - "titanium_boots;false"
  - "titanium_chestplate;false"
  - "titanium_helmet;false"
  - "titanium_hoe;true"
  - "titanium_ingot;false"
  - "titanium_leggings;false"
  - "titanium_pickaxe;true"
  - "titanium_raw_ore;false"
  - "titanium_spade;true"
  - "titanium_sword;true"
  - "vanilla_cookie;false"
  - "vanilla_cream;false"
  - "vanilla_cupcake;false"
  - "vanilla_extract;false"
  - "weed_leaf;false"
  - "weed_seed;false"
# Allow connections from ProxyPass and Waterdog.
# See https://www.spigotmc.org/wiki/firewall-guide/ for assistance - use UDP instead of TCP.
enable-proxy-connections: false

# The internet supports a maximum MTU of 1492 but could cause issues with packet fragmentation.
# 1400 is the default.
mtu: 1400

# Whether to connect directly into the Java server without creating a TCP connection.
# This should only be disabled if a plugin that interfaces with packets or the network does not work correctly with Geyser.
# If enabled on plugin versions, the remote address and port sections are ignored
# If disabled on plugin versions, expect performance decrease and latency increase
use-direct-connection: true

config-version: 4
